### ISSUE TITLE
Memory leak when not calling Span::End

### ISSUE THREAD

**Issue by Oberon00** [census-instrumentation/opencensus-cpp#303] opened 2019-03-20 12:49 UTC
In the constructor, a span adds itself to the running span store. However, it is only removed from there in End(). Since a span has no user-defined destructor, this leads to a memory leak if End() is not called on the span.

**Comment by g-easy** [comment] 2019-04-05 01:52
This is by design. Spans are not RAII, although we are considering adding a ScopedSpan wrapper around Span.

**Comment by Oberon00** [comment] 2019-04-05 06:49
I understand that spans should not end themselves automatically, but leaking them in the running span store still sounds like a bug to me.

**Comment by g-easy** [comment] 2019-04-05 07:44
The running span store holds all active spans, and is intended for e.g. building z-pages.

My view is that leaking a Span is not different from leaking an object - it's a bug in the caller and not something we should try to "mitigate."

**Comment by jinmel** [comment] 2019-06-24 04:46
Could we close this issue since we can address this issue with #327?

**Comment by g-easy** [comment] 2019-06-24 05:24
I think so.

**Closed by g-easy** 2019-06-24 05:24 UTC
